# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 115f97e41f32f9b805dafd4142043f81f253ebaf3d12455b63627019bd92dac7d6685cb21efe232de1ecd75a42d992e342a1ca115419a0e5834fcf70f64de31a

test:
  secret_key_base: d8a1269968292ff22d732b55653d0079a19d579605cb366d036859049d102ca76a05eae8fc71ff2247ba8b9280c376431c41644ce9c15d6adc917db4e5eb3eb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
